POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "pyaesone",
  "password": "abc123"
}

### Get Users
GET http://localhost:3000/users/600076a640ffdf6be1dd9a9f

### Save User
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "pyaesonenew",
  "password": "abc123"
}

### Delete User
DELETE http://localhost:3000/users/6000659b40ffdf6be1dd9a9e

### Get All Industries
GET http://localhost:3000/industries

### Save Industries
POST http://localhost:3000/industries
Content-Type: application/json

{
  "name": "Yoma Bank",
}

###
GET http://localhost:3000/industries/5ffadb3208ef5346cec91613

###
PATCH  http://localhost:3000/industries/5ffadb3208ef5346cec91613
Content-Type: application/json

{
  "name": "KBZ Bank"
}

POST http://localhost:3000/groups
Content-Type: application/json

{
  "name": "Group Name",
  "url": "https://www.facebook.com",
  "picture_url": "https://dummyimage.com/600x400/000/fff&text=DBImage",
  "industry_id": "5ffadb3208ef5346cec91613"
}

###
POST http://localhost:3000/groups
Content-Type: application/json

{
  "name": "Group Name",
  "url": "https://www.facebook.com",
  "industry_id": "6001993b9bbd588ead5ba0c8"
}

###
GET http://localhost:3000/industries

###
POST http://localhost:3000/industries
Content-Type: application/json

{
  "name": "Samsung"
}

###
GET http://localhost:3000/groups

###
GET http://localhost:3000/groups/6001994c9bbd588ead5ba0ca


